### ISSUE TITLE
Feature: implement a readable stream API

### ISSUE THREAD

**Issue by ofrobots** [v8/sampling-heap-profiler#1]
Right now we offer `write` which outputs a file. It would be nice to offer a readable stream so that the users can route the data to a destination of their choosing.

**Comment by jkrems** [comment]
Would it make sense to maybe even expose the data itself? Then people would be free to chose different trade-offs (e.g. using incremental serialization that's spread out instead of one big `JSON.stringify`).

**Comment by ofrobots** [comment]
@jkrems: that is a good suggestion. Added a `get` method. See #4 for type definitions.

**Comment by nolanmar511** [comment]
This repo is being archived (see https://github.com/v8/sampling-heap-profiler/blob/master/README.md for more information).

Closing all issues in anticipation of this.
