### ISSUE TITLE
Misattribution of allocated memory?

### ISSUE THREAD

**Issue by nolanmar511** [v8/sampling-heap-profiler#16]
I'm collecting profiles of this benchmark:

```
const startTime = Date.now();
const testArr = [];
let callCount = 0;

function alloc() {
  for (let i = 0; i < 500; i++) {
    testArr[i] = new Array(2^11);
    for (let j=0; j < testArr[i].length; j++) {
      testArr[i][j] = i * j;
    }
  }
}

/**
 * Fills several arrays, then calls itself with setImmediate.
 * It continues to do this until durationSeconds after the startTime.
 */
function busywork(durationSeconds) {
  for (let i = 0; i < testArr.length; i++) {
    for (let j = 0; j < testArr[i].length; j++) {
      Math.sqrt(j * testArr[i][j]);
    }
  }
  if (Date.now() - startTime < 1000 * durationSeconds) {
    setTimeout(() => busywork(durationSeconds), 5);
  }
}

const durationSeconds = process.argv.length > 2 ? process.argv[2] : 600; 

alloc();
busywork(durationSeconds);
```

I would have expected to see `alloc()` appear in the heap profile, but instead when profiling this, I first saw this profile:
![first](https://user-images.githubusercontent.com/14046562/37296859-66ec3f34-25d9-11e8-92f3-9d34087a7de6.png).

It looks like the memory allocation is being attributed to `busywork()` instead of alloc. 

@ofrobots  -- is this expected behavior?

**Comment by ofrobots** [comment]
That is curious indeed. I am not sure if it is a misattribution though. If I change the 500 to a 5000 in that test, alloc does show up. I am investigating why we failed to sample it with a loop count of 500.

**Comment by ofrobots** [comment]
For completeness, this is what I observe when I use loop count of 5000:

![image](https://user-images.githubusercontent.com/79017/37306920-7daed5b6-25f6-11e8-9add-98b915b02f7b.png)

**Comment by ofrobots** [comment]
Found the issue. `testArr[i] = new Array(2^11);` is an array of length 9. `^` doesn't do what you intended.

**Comment by ofrobots** [comment]
Changing it to `2 ** 11` solves the problem.

**Comment by nolanmar511** [comment]
Thanks -- I'm still having a tough time generating profiles with cloud-profiler-nodejs where the `alloc` function appears, but hopefully this will help.
