### ISSUE TITLE
npm install fails if Python is not installed

### ISSUE THREAD

**Issue by Kwooda** [v8/sampling-heap-profiler#19]
In some environments (in my case, reported under Windows 10), npm install is giving an error that Python executable is not found, and node-gyp fails. In locked-down computers is enterprise settings, we cannot easily install Python to get around this. Please provide a pre-built binary to avoid the build during install.

**Comment by nolanmar511** [comment]
This repo is being archived (see https://github.com/v8/sampling-heap-profiler/blob/master/README.md for more information). 

Closing all issues in anticipation of this.

**Comment by nolanmar511** [comment]
This repo is being archived (see https://github.com/v8/sampling-heap-profiler/blob/master/README.md for more information).

Closing all issues in anticipation of this.
