### ISSUE TITLE
Improve square complexity in weak callback

### ISSUE THREAD

**Issue by ofrobots** [v8/sampling-heap-profiler#20]
Sampling heap profiler has polynomial complexity in the number of active samples in the weak callback. This resulted in pathological pause times due to a bug in GC that was causing dead weak handles from being scavenged: https://bugs.chromium.org/p/chromium/issues/detail?id=847863.

While the root cause (GC issue) has been fixed, it would still be good to avoid the square complexity in the weak callback if possible.

**Comment by nolanmar511** [comment]
This repo is being archived (see https://github.com/v8/sampling-heap-profiler/blob/master/README.md for more information). 

Closing all issues in anticipation of this.
