### ISSUE TITLE
Allow writing to file path rather than just file name in working directory

### ISSUE THREAD

**Issue by jazoom** [v8/sampling-heap-profiler#22]
Today I had to write the file, then move it to another directory. That is a minor annoyance, but it became 2 minor annoyances since the server runs in a Kubernetes cluster and Node's `fs.rename` function cannot actually handle moving a file from within Docker to the host.

It would have been much simpler if I was able to just choose the path to dump the heap profile to in the first place.

Also, I'd like to say a massive **thank you** for creating this library. It worked perfectly. Today I solved 3 memory leaks (multiple projects) within a few hours that I previously was unable to find with days of using inferior techniques. The flame graph of calling functions is great. I was unable to reproduce these leaks in development so this being designed to run in prod was very helpful. You have saved me time and headaches.

**Comment by aalexand** [comment]
Thanks for the kind words. Slightly off-topic, but consider using https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs which is an agent for Stackdriver Profiler - a tool to continuous gather performance data from production so that they can be analyzed any time.

**Comment by kenashcraft** [comment]
It works for me to write to another directory. Just pass the full path to the filename argument of `write`.

**Comment by jazoom** [comment]
Thanks @aalexand but I don't use Google Cloud for anything at the moment.

**Comment by jazoom** [comment]
Thanks @ofrobots. I'm sure this library will help thousands of developers into the future.

**Comment by ofrobots** [comment]
It would be useful if you have some repro steps for where the write didn't work.

**Comment by jazoom** [comment]
I'm pretty sure I was just being stupid and used `C:\...` instead of `/mnt/c/...`, or something like that. If you're using fs.writeFile it should be okay, since I've used that without issue before.

**Comment by ofrobots** [comment]
I've opened PR https://github.com/v8/sampling-heap-profiler/pull/24 to address the docs for the `write` function. I'm going to close this issue as I think it is addressed. Please do add a comment if you feel otherwise.
