### ISSUE TITLE
Data format documentation

### ISSUE THREAD

**Issue by mcollina** [v8/sampling-heap-profiler#30]
Where is the data format documented? Can you please add a link?

**Comment by ofrobots** [comment]
The generated file is in the format used by Chrome DevTools - so one can open it in Chrome DevTools. Let me see if I can find some documentation for it.

**Comment by mcollina** [comment]
Thanks!

**Comment by nolanmar511** [comment]
This repo is being archived (see https://github.com/v8/sampling-heap-profiler/blob/master/README.md for more information). 

Closing all issues in anticipation of this.
